# Generated by Django 5.2.5 on 2025-08-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='TipoLavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('preco_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tipo de Lavagem',
                'verbose_name_plural': 'Tipos de Lavagem',
            },
        ),
        migrations.CreateModel(
            name='TransporteEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('multiplicador_preco', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Transporte/Equipamento',
                'verbose_name_plural': 'Transportes/Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Lavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do Veículo')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de Início')),
                ('hora_termino', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Término')),
                ('data_lavagem', models.DateField(verbose_name='Data da Lavagem')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Lavagem em Andamento'), ('CONCLUIDA', 'Lavagem Concluída'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Serviço')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('recebimento', models.CharField(blank=True, max_length=200, verbose_name='Recebimento')),
                ('contrato', models.CharField(blank=True, help_text='Número ou código do contrato', max_length=100, verbose_name='Contrato')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens_base', to='lavagens.base')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens', to='clientes.cliente')),
                ('lavador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens', to='clientes.lavador')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens', to='clientes.veiculo')),
                ('tipo_lavagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens_tipo', to='lavagens.tipolavagem')),
                ('transporte_equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens_transporte', to='lavagens.transporteequipamento')),
            ],
            options={
                'verbose_name': 'Lavagem',
                'verbose_name_plural': 'Lavagens',
                'ordering': ['-data_lavagem', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('base', models.CharField(blank=True, max_length=100, verbose_name='Base')),
                ('local', models.CharField(blank=True, max_length=100, verbose_name='Local')),
                ('tipo_lavagem', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Lavagem')),
                ('transporte_equipamento', models.CharField(blank=True, max_length=50, verbose_name='Transporte/Equipamento')),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do Veículo')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('hora_agendamento', models.TimeField(verbose_name='Hora do Agendamento')),
                ('duracao_estimada', models.PositiveIntegerField(default=30, help_text='Tempo estimado para conclusão da lavagem', verbose_name='Duração Estimada (minutos)')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não Compareceu')], default='AGENDADO', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado da lavagem', max_digits=10, null=True, verbose_name='Valor Estimado')),
                ('desconto_agendamento', models.DecimalField(decimal_places=2, default=0, help_text='Desconto especial por agendar', max_digits=10, verbose_name='Desconto por Agendamento')),
                ('telefone_contato', models.CharField(blank=True, help_text='Telefone para confirmação do agendamento', max_length=20, verbose_name='Telefone de Contato')),
                ('email_contato', models.EmailField(blank=True, help_text='Email para envio de confirmações', max_length=254, verbose_name='Email de Contato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, help_text='Observações visíveis apenas para funcionários', verbose_name='Observações Internas')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('confirmado_por', models.CharField(blank=True, max_length=100, verbose_name='Confirmado por')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('cliente', models.ForeignKey(help_text='Cliente que solicitou o agendamento', on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.cliente')),
                ('lavador', models.ForeignKey(blank=True, help_text='Lavador designado (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.lavador')),
                ('veiculo', models.ForeignKey(blank=True, help_text='Veículo a ser lavado (opcional se apenas placa)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.veiculo')),
                ('lavagem', models.OneToOneField(blank=True, help_text='Lavagem criada a partir deste agendamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamento_origem', to='lavagens.lavagem')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_agendamento', 'hora_agendamento'],
                'unique_together': {('data_agendamento', 'hora_agendamento', 'local')},
            },
        ),
    ]
