# Generated by Django 5.2.5 on 2025-08-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavagens', '0002_lavagem_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='lavagens.base'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_lavagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='lavagens.tipolavagem'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='transporte_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='lavagens.transporteequipamento'),
        ),
    ]
