# Generated by Django 5.2.5 on 2025-09-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavagens', '0003_alter_agendamento_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_lavagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='lavagens.tipolavagem')),
            ],
            options={
                'verbose_name': 'Material da Lavagem',
                'verbose_name_plural': 'Materiais da Lavagem',
            },
        ),
    ]
