# Generated by Django 5.2.5 on 2025-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cpf_cnpj_remove_cliente_endereco'),
        ('lavagens', '0004_materiallavagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavagem',
            name='lavador',
        ),
        migrations.AddField(
            model_name='lavagem',
            name='lavador',
            field=models.ManyToManyField(blank=True, related_name='lavagens', to='clientes.lavador'),
        ),
    ]
