# Generated by Django 5.2.5 on 2025-09-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavagens', '0005_remove_lavagem_lavador_lavagem_lavador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavagem',
            old_name='lavador',
            new_name='lavadores',
        ),
    ]
