# Generated by Django 5.2.5 on 2025-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cpf_cnpj_remove_cliente_endereco'),
        ('lavagens', '0006_rename_lavador_lavagem_lavadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='lavador',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='lavadores',
            field=models.ManyToManyField(blank=True, help_text='Lavadores designados (opcional)', related_name='agendamentos', to='clientes.lavador'),
        ),
    ]
