# Generated by Django 5.2.5 on 2025-08-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
    ]
