# Generated by Django 5.2.5 on 2025-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cpf_cnpj_remove_cliente_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lavador',
            options={'ordering': ['nome'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='lavador',
            name='escala_trabalho',
            field=models.CharField(blank=True, help_text='Ex: 5x2, 6x1', max_length=50, verbose_name='Escala'),
        ),
        migrations.AddField(
            model_name='lavador',
            name='jornada_trabalho',
            field=models.CharField(blank=True, help_text='Ex: Seg a Sex, 08:00 às 17:00', max_length=100, verbose_name='Jornada de Trabalho'),
        ),
        migrations.AddField(
            model_name='lavador',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='lavador',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
    ]
