# Generated by Django 5.2.5 on 2025-11-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_lavador_options_lavador_escala_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lavador',
            options={'ordering': ['nome'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores (RH)'},
        ),
    ]
