# Generated by Django 5.2.5 on 2025-11-21 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='lavador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavador_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
        migrations.AlterField(
            model_name='lavador',
            name='escala_trabalho',
            field=models.CharField(blank=True, max_length=50, verbose_name='Escala'),
        ),
        migrations.AlterField(
            model_name='lavador',
            name='jornada_trabalho',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jornada de Trabalho'),
        ),
    ]
