# Generated by Django 5.2.5 on 2025-11-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_lavador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, verbose_name='Número da Nota')),
                ('cnpj_fornecedor', models.CharField(max_length=18, verbose_name='CNPJ Fornecedor')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_total_nota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total da Nota')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Arquivo da NF')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota Fiscal (Entrada)',
                'verbose_name_plural': 'Financeiro - Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(default='UN', max_length=20, verbose_name='Unidade')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('quantidade_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Médio (Unit)')),
            ],
            options={
                'verbose_name': 'Produto/Insumo',
                'verbose_name_plural': 'Estoque - Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Comprada')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total_item', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total do Item')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.notafiscalentrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.produto')),
            ],
            options={
                'verbose_name': 'Item da Nota',
                'verbose_name_plural': 'Itens da Nota',
            },
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Retirada')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data de Saída')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Uso na lavagem premium', max_length=200, verbose_name='Motivo/Uso')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.produto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.lavador', verbose_name='Responsável (Colaborador)')),
            ],
            options={
                'verbose_name': 'Saída de Material',
                'verbose_name_plural': 'Estoque - Saídas',
            },
        ),
    ]
