# Generated by Django 5.2.5 on 2025-11-21 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_lavador_options'),
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Prateleira A1, Armário 2', max_length=50, verbose_name='Nome/Identificação')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
            },
        ),
        migrations.AlterModelOptions(
            name='itemnotafiscal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notafiscalentrada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto do Estoque', 'verbose_name_plural': 'Catálogo de Produtos'},
        ),
        migrations.RenameField(
            model_name='notafiscalentrada',
            old_name='data_registro',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='itemnotafiscal',
            name='valor_total_item',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('CONSUMIVEL', 'Consumível (Sabão, Cera, etc.)'), ('DURAVEL', 'Durável/Ferramenta (Politriz, etc.)')], default='CONSUMIVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.notafiscalentrada'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Médio'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.localarmazenamento', verbose_name='Localização Física'),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/NF)'), ('SAIDA', 'Saída (Uso/Retirada)'), ('DEVOLUCAO', 'Devolução ao Estoque'), ('AJUSTE', 'Ajuste de Inventário/Perda')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo_anterior', models.IntegerField(editable=False)),
                ('saldo_atual', models.IntegerField(editable=False)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação/Motivo')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.notafiscalentrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.produto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.lavador', verbose_name='Colaborador Responsável')),
                ('usuario_sistema', models.ForeignKey(help_text='Usuário que registrou no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Movimentação',
                'verbose_name_plural': 'Histórico de Movimentações',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.DeleteModel(
            name='SaidaEstoque',
        ),
    ]
